name: sunmi_printer_extra
description: "Support V2 Pro Sunmi Label Version and Null safety. With this package you can connect with Sunmi printers, print text, image, qrcode, barcodes and a custom Esc/Pos if you like."
version: 1.0.0
homepage: https://github.com/iamngoni/sunmi_printer_extra/

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: co.modestnerd.sunmi_printer_extra
        pluginClass: SunmiPrinterPlugin
      ios:
        pluginClass: SunmiPrinterPlusPlugin